### ISSUE TITLE
Not yet implemented error

### ISSUE THREAD

**Issue by damionx7** [nextcloud/android-library#1135]
I am using version `2.14.0` and I am getting this error. How can I resolve this ?

```
 ExistenceCheckRemoteOperation operation = new ExistenceCheckRemoteOperation(loginModel.getUrl(), false);
var result = operation.execute(client);
```

```
NetworkUtils               D  Searching known-servers store at /data/user/0/org.eu.thedoc.zettelnotes.debug/files/knownServers.bks
ExistenceCh...teOperation  D  Not yet implemented
NextcloudDialogFragment    E  java.lang.UnsupportedOperationException: Not yet implemented
                              	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:110)
                              	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:220)
                              	at org.eu.thedoc.zettelnotes.common.dialog.NextcloudDialogFragment.checkConnection(NextcloudDialogFragment.java:212)
                              	at org.eu.thedoc.zettelnotes.common.dialog.NextcloudDialogFragment.lambda$onCreateDialog$5(NextcloudDialogFragment.java:151)
                              	at org.eu.thedoc.zettelnotes.common.dialog.NextcloudDialogFragment.$r8$lambda$lvwu8ZIQ5OI5VbTlFGrgnBPANT8(Unknown Source:0)
                              	at org.eu.thedoc.zettelnotes.common.dialog.NextcloudDialogFragment$$ExternalSyntheticLambda9.run(Unknown Source:2)
                              	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                              	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                              	at java.lang.Thread.run(Thread.java:1013)
```

**Comment by damionx7** [comment]
Thanks for replying.

Now I get this error

`  class file for org.apache.commons.httpclient.HttpClient not found`

**Comment by damionx7** [comment]
I guess I need to add 
`   implementation "commons-httpclient:commons-httpclient:3.1@jar" // remove after entire switch to lib v2`
