### ISSUE TITLE
Library crashes at authorization using Android 9

### ISSUE THREAD

**Issue by gerritbeuze** [nextcloud/android-library#336]
After I updated my project to Android 9 (API 28) the library no longer works as it crashes
due to a class not being to load NTLMScheme

I have included the legacy library in the project

` useLibrary 'org.apache.http.legacy'`

other clouds (Google Drive api, Dropbox api etc) depending on this library work OK, it's just the authorization that does not work.

I checked the contents of the legacy .jar and see the class is inside that .jar, but  seems at a different path. Any ide how to fix this?

```
     Caused by: java.lang.NoClassDefFoundError: org.apache.commons.httpclient.auth.NTLMScheme
        at org.apache.commons.httpclient.auth.AuthPolicy.class$(AuthPolicy.java:100)
        at org.apache.commons.httpclient.auth.AuthPolicy.<clinit>(AuthPolicy.java:100)
        at org.apache.commons.httpclient.auth.AuthPolicy.getAuthScheme(Unknown Source:0)
        at org.apache.commons.httpclient.auth.AuthState.setPreemptive(AuthState.java:122)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:162)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:222)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
        at com.owncloud.android.lib.resources.files.ExistenceCheckRemoteOperation.run(ExistenceCheckRemoteOperation.java:91)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
```

**Comment by tobiasKaminsky** [comment]
Hm. We have this explicitly disabled:
https://github.com/nextcloud/android/blob/e8846252406a5df757800a891c2f9dc347330b31/src/main/AndroidManifest.xml#L101-L103

**Comment by gerritbeuze** [comment]
That's in the android manifest where you declare that the library is enabled but not required (for on lower android versions it is not available). I have the same in my manifest. I'm talking about the library, not the app. I use the library to sign in and perform as test call like so:

```
// Some AsyncTask
		protected RemoteOperationResult doInBackground(Void... params) {
			OwnCloudCredentials credentials = new OwnCloudBasicCredentials(_authData.username, _authData.password);
			Uri uri = Uri.parse(_authData.server); // server is the server https://.... without remote.php/
			OwnCloudClient client = OwnCloudClientFactory.createOwnCloudClient(uri, Application.getAppContext(), true);
			client.setCredentials(credentials);
			if (true) {
     // Attempt to read contents of the root folder
				ReadRemoteFolderOperation refreshOperation = new ReadRemoteFolderOperation("/");
				return refreshOperation.execute(client); // <-- Here it crashes
			}

```
```
D/OwnCloudClient #0: Creating OwnCloudClient
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
D/OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.owncloud.android.lib.common.operations.RemoteOperationResult.isSuccess()' on a null object reference
        at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:110)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)

```

**Comment by tobiasKaminsky** [comment]
Can you provide this test somewhere, so that I can run it directly?
ReadRemoteFolderOperation also indicates that you use an old library, as in latest 1.5.0 release it is already called ReadFolderRemoteOperation.

**Comment by gerritbeuze** [comment]
This is how I include the library:
`    implementation 'com.github.nextcloud:android-library:master'`
That should give me the latest version?

As for a test: after letting the user enter server and username + pwd there's an ASyncTask started that does this - there's not much more to it that just that. You can even enter the credential in source:

```
		@Override
		protected RemoteOperationResult doInBackground(Void... params) {
			OwnCloudCredentials credentials = new OwnCloudBasicCredentials(_authData.username, _authData.password);
			Uri uri = Uri.parse(_authData.server);
			OwnCloudClient client = OwnCloudClientFactory.createOwnCloudClient(uri, SimpleMindApp.getAppContext(), true);
			client.setCredentials(credentials);
			if (true) {
				ReadRemoteFolderOperation refreshOperation = new ReadRemoteFolderOperation("/");
				return refreshOperation.execute(client);
			}
			else {
				ExistenceCheckRemoteOperation operation = new ExistenceCheckRemoteOperation(NextcloudProvider.WebDAVRootFolder, 
// I pass a reference to the app context in the constructor
Application.getAppContext(), false);
				return operation.execute(client);
			}
		}
```

**Comment by gerritbeuze** [comment]
After renaming all classes in my code to the 1.5.0 names I am now back to the original problem:

`java.lang.NoClassDefFoundError: org.apache.commons.httpclient.auth.NTLMScheme`

Log below, any ideas?


```
D/OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/
E/ReadFolderRemoteOperation: Synchronized /: failed
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.modelmakertools.simplemindpro, PID: 6169
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: org.apache.commons.httpclient.auth.NTLMScheme
        at org.apache.commons.httpclient.auth.AuthPolicy.class$(AuthPolicy.java:100)
        at org.apache.commons.httpclient.auth.AuthPolicy.<clinit>(AuthPolicy.java:100)
        at org.apache.commons.httpclient.auth.AuthPolicy.getAuthScheme(Unknown Source:0)
        at org.apache.commons.httpclient.auth.AuthState.setPreemptive(AuthState.java:122)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:162)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:221)
        at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:80)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:138)
        at com.modelmakertools.simplemindpro.clouds.nextcloud.NextcloudAuthorizationActivity$AuthTesterTask.doInBackground(NextcloudAuthorizationActivity.java:51)
        at com.modelmakertools.simplemindpro.clouds.nextcloud.NextcloudAuthorizationActivity$AuthTesterTask.doInBackground(NextcloudAuthorizationActivity.java:32)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by gerritbeuze** [comment]
As suspected, this is a packaging problem. I was able to get it working by adding this to the proguard-rules.pro

```
-keep class org.apache.commons.httpclient.auth.** { *; }
-keep class org.apache.commons.httpclient.cookie.** { *; }
```

Note, that this does *not* work (allowshrinking breaks it again)
```
-keep,allowshrinking class org.apache.commons.httpclient.auth.** { *; }
-keep,allowshrinking class org.apache.commons.httpclient.cookie.** { *; }

```
