### ISSUE TITLE
Crash when trying to execute ReadFolderRemoteOperation

### ISSUE THREAD

**Issue by helgovic** [nextcloud/android-library#711]
I have followed the instructions from the sample application, for calling ReadFolderRemoteOperation but i get this error.

```
java.lang.ExceptionInInitializerError
        at org.apache.jackrabbit.webdav.Status.<init>(Status.java:41)
        at org.apache.jackrabbit.webdav.MultiStatusResponse.getStatus(MultiStatusResponse.java:262)
        at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:119)
        at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:144)
        at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:88)
        at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.Reader.read(char[])' on a null object reference
        at java.util.Properties$LineReader.readLine(Properties.java:432)
        at java.util.Properties.load0(Properties.java:348)
        at java.util.Properties.load(Properties.java:336)
        at org.apache.jackrabbit.webdav.DavException.<clinit>(DavException.java:41)
        at org.apache.jackrabbit.webdav.DavException.getStatusPhrase(DavException.java:131)
        at org.apache.jackrabbit.webdav.Status.<init>(Status.java:41) 
        at org.apache.jackrabbit.webdav.MultiStatusResponse.getStatus(MultiStatusResponse.java:262) 
        at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:119) 
        at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:144) 
        at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:88) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363) 
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by tobiasKaminsky** [comment]
This seems to be a webdav error.
Can you post the code what lead to this error?
